# LOCAL HOST

# GET A SINGLE USER
###
http://localhost:3000/users/63dd05a9876d194ec8741694
###
http://localhost:3000/api-docs/#/

# GET ALL USERS
###
GET http://localhost:3000/users/

# REGISTER A USER
###
POST http://localhost:3000/users/
Content-Type: application/json

{
    "firstName": "valiadtot",
    "lastName": "Mule",
    "userEmail": "johnoioio@gmail.com",
    "password": "123456",
    "birthday":"18/05/19",
    "gender": "male",
    "favoriteQuote": ""
}

# GET A SINGLE POST
###
http://localhost:3000/posts/63e7b570e0e17c1f11a15758

# GET ALL POSTS
###
GET http://localhost:3000/posts

# CREATE A POST
###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Shani apo-2!",
    "description": "always working!",
    "postCategory": "moving",
    "userId": "63e7b249e0e17c1f11a1574a",
    "userEmail": "simy@gmail.com"
}

# UPDATE A POST
###
PUT http://localhost:3000/posts/63e7f93deadc6b5ce85c7d44
Content-Type: application/json

{
    "title": "Shani apo-2-updated!",
    "description": "always working!",
    "postCategory": "moving",
    "userId": "63e7b249e0e17c1f11a1574a",
    "userEmail": "simy@gmail.com"
}

# DELETE A POST
###
DELETE http://localhost:3000/posts/63e7f93deadc6b5ce85c7d44
Content-Type: application/json

{
    "userId": "63e7b249e0e17c1f11a1574a"
}

# DISPLAY AND INTERACT WITH THE CONTACTS API DOCUMENTATION - USE BROWSER FOR THIS ROUTE


#ON RENDER
###
https://cse341-blog-api-service.onrender.com/api-docs/#/

# GET A SINGLE USER
###
https://cse341-blog-api-service.onrender.com/users/63dd05a9876d194ec8741694

# GET ALL USERS
###
GET https://cse341-blog-api-service.onrender.com/users/

# REGISTER A USER
###
POST https://cse341-blog-api-service.onrender.com/users/
Content-Type: application/json

{
    "firstName": "Mule",
    "lastName": "kabwe",
    "email": "mul@gmail.com",
    "password": "123456",
    "birthday":"18/05/19",
    "gender": "male",
    "favoriteQuote": ""
}

# GET A SINGLE POST
###
GET https://cse341-blog-api-service.onrender.com/posts/63e7b570e0e17c1f11a1575812

# GET ALL POSTS
###
GET https://cse341-blog-api-service.onrender.com/posts/

# CREATE A POST
###
POST https://cse341-blog-api-service.onrender.com/posts/
Content-Type: application/json

{
    "title": "Shani apo-2!",
    "description": "always working!",
    "postCategory": "moving",
    "userId": "63e7b249e0e17c1f11a1574a",
    "userEmail": "simy@gmail.com"
}

# UPDATE A POST
###
PUT https://cse341-blog-api-service.onrender.com/posts/63e7badf0009cab9335bfbf4
Content-Type: application/json

{
    "title": "Shani apo-2-updated!",
    "description": "always working!",
    "postCategory": "moving",
    "userId": "63e7b249e0e17c1f11a1574a",
    "userEmail": "simy@gmail.com"
}

# DELETE A POST
###
DELETE https://cse341-blog-api-service.onrender.com/63e7b570e0e17c1f11a15758
Content-Type: application/json

{
    "userId": "63e7b249e0e17c1f11a1574a"
}
